# Generated by Django 4.2.1 on 2023-11-26 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_auth', models.BooleanField(default=False)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_conference_admin', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=70, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('reviewer_id', models.IntegerField(default=0)),
                ('reviewer_name', models.CharField(max_length=70)),
                ('highest_qualification', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
                ('designations', models.CharField(max_length=70)),
                ('organization', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reviewer_number', models.CharField(max_length=15)),
                ('whats_app_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=250)),
                ('date_reviewer', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_upload', models.FileField(upload_to='reviewer/profile-photos/')),
                ('resume_upload', models.FileField(upload_to='reviewer/profile-resume/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_ok', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='reviewerdata_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='reviewerdata_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='resubmit_papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('title_paper', models.CharField(max_length=70)),
                ('Auth_name', models.CharField(max_length=70)),
                ('paper_description', models.CharField(max_length=500)),
                ('paper_upload', models.FileField(upload_to='papers/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('has_uploaded_paper', models.BooleanField(default=False)),
                ('Auth_email', models.EmailField(default='example@example.com', max_length=254)),
                ('Auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('Auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('corresponding_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('corresponding_auth_email', models.EmailField(default='corresponding@example.com', max_length=254)),
                ('corresponding_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('corresponding_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('other_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('other_auth_email', models.CharField(default='other@example.com', max_length=150)),
                ('other_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('other_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('paper_keyword', models.CharField(default='No keywords', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('comment1', models.CharField(default='Not Available', max_length=1000)),
                ('comment2', models.CharField(default='Not Available', max_length=1000)),
                ('comment3', models.CharField(default='Not Available', max_length=1000)),
                ('reviewer_comments', models.JSONField(blank=True, default=dict)),
                ('assigned_reviewers', models.ManyToManyField(related_name='resubmit_papers', to='users.reviewer_data')),
                ('conference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='conference.conference')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_title', models.CharField(max_length=255)),
                ('contribution_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=20)),
                ('content_type', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('paper_upload', models.FileField(upload_to='papers/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('has_uploaded_paper', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('comment1', models.CharField(default='Not Available', max_length=1000)),
                ('comment2', models.CharField(default='Not Available', max_length=1000)),
                ('comment3', models.CharField(default='Not Available', max_length=1000)),
                ('reviewer_comments', models.JSONField(blank=True, default=dict)),
                ('assigned_reviewers', models.ManyToManyField(related_name='assigned_papers', to='users.reviewer_data')),
                ('authors', models.ManyToManyField(to='users.author')),
                ('conference', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='conference.conference')),
                ('main_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.conferencetopic')),
                ('other_topics', models.ManyToManyField(blank=True, related_name='papers', to='conference.conferencetopic')),
                ('track_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.conferencetrack')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
