# Generated by Django 4.2.1 on 2023-11-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contribution_title_paper_title_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='contribution_type',
            field=models.CharField(choices=[('type1', 'Article'), ('type2', 'Presentation Orale')], max_length=20),
        ),
    ]
