# Generated by Django 4.2.1 on 2023-11-26 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=80)),
                ('conference_descriptions', models.CharField(max_length=600)),
                ('conference_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('conference_end_date', models.DateField()),
                ('conference_venue', models.CharField(default='online', max_length=250, null=True)),
                ('conference_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('conference_user', models.CharField(default='Not present', max_length=150)),
                ('has_uploaded_paper', models.BooleanField(default=False)),
                ('topics', models.ManyToManyField(blank=True, related_name='conferences', to='conference.conferencetopic')),
                ('tracks', models.ManyToManyField(blank=True, related_name='conferences', to='conference.conferencetrack')),
            ],
        ),
    ]
